version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

  settings:
    errcheck:
      check-type-assertions: true

run:
  timeout: 5m
